Repository jyoo980/silver, pull requests merged in 2020-12, with the labels that each got.

#19 adding initial implementation of permission passthrough
  src/main/scala/viper/silver/plugin/standard/inline/InlinePredicatePlugin.scala
  src/main/scala/viper/silver/plugin/standard/inline/InlineRewrite.scala
  src/main/scala/viper/silver/plugin/standard/inline/PredicateExpansion.scala
  src/test/scala/plugin/inline/PredicateExpansionTest.scala
Labels: bug

#5 adding first pass at mutual-recursion detection
  src/main/scala/viper/silver/plugin/CallGraph.scala
  src/main/scala/viper/silver/plugin/standard/inline/InlineErrorChecker.scala
  src/main/scala/viper/silver/plugin/standard/inline/InlinePredicatePlugin.scala
  src/main/scala/viper/silver/plugin/standard/inline/PredicateCallGraph.scala
  src/test/scala/plugin/inline/InlineErrorCheckerTest.scala
Labels: enhancement

#31 adding test files
  vpr-test-files/impure-branch.vpr
  vpr-test-files/inline.vpr
  vpr-test-files/mutrec.vpr
  vpr-test-files/nested.vpr
  vpr-test-files/recursive.vpr
  vpr-test-files/sum.vpr
  vpr-test-files/tuple.vpr
Labels: testing

#37 Fix incorrect permission propagation (should be multiplicative)
  src/main/scala/viper/silver/plugin/standard/inline/PredicateExpansion.scala
  vpr-test-files/permission-propagation.vpr
Labels: bug

#39 Check if predicate body is defined in cond.
  src/main/scala/viper/silver/plugin/standard/inline/InlinePredicatePlugin.scala
Labels: bug

#42 Check for recursive predicates using /all/ existing predicates.
  src/main/scala/viper/silver/plugin/standard/inline/InlinePredicatePlugin.scala
Labels: bug

#40 Turn fold/unfold statements into assert statements.
  src/main/scala/viper/silver/plugin/standard/inline/InlineRewrite.scala
Labels: enhancement

#44 Recursively call expandPredicate on current node.
  src/main/scala/viper/silver/plugin/standard/inline/InlineRewrite.scala
Labels: bug
